name: concatenate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.2

      - name: Concatenate files
        uses: ftnext/action-concatenate-files@v1.0.1
        with:
          sources: example/item1.txt example/item2.txt
          destination: example/item3.txt

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0

