name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.2

      - name: Download a file
        uses: carlosperate/download-file-action@v2
        id: download-file
        with:
          file-url: 'https://raw.githubusercontent.com/carlosperate/download-file-action/master/README.md'
          file-name: 'asdasd.txt'
          location: './new-folder-to-be-created'
      - name: Print the file path (new-folder-to-be-created/new_filename.tar.gz)
        run: echo "The file was downloaded to ${{ steps.download-file.outputs.file-path }}"

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0

