name: Update File
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Download Upload
        uses: wow-actions/download-upload@v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: https://raw.githubusercontent.com/Mango2Juice/Test1/main/test/test1.txt
          dir: Download
          filename: raw.txt