name: Download Upload
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: wow-actions/download-upload@v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: https://raw.githubusercontent.com/wow-actions/download-upload/master/.github/workflows/download-upload.yml
          dir: demo