name: overwrite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format-code:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.2

      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: ci/test-output/out.js
          write-mode: overwrite
          contents: |
            console.log('some contents: ${{github.ref_name}}')
            console.log('some contents: ${{ vars.JOB_NAME }}')

      - name: Concatenate files
        uses: ftnext/action-concatenate-files@v1.0.1
        with:
          sources: example/item1.txt example/item2.txt
          destination: example/item3.txt
            
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0

