name: concatenate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.2

      - name: Concatenate files
        uses: https://github.com/Mango2Juice/Test1@main
        with:
          sources: example/item1.txt example/item2.txt
          destination: example/item3.txt

