name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.2

      - name: Write File
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: test-output/out.js
          write-mode: overwrite
          contents: |
            Hello World!
      
      - name: Push changes
        uses: actions-go/push@v1