name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.2

      - name: Concatenate files
        uses: Mango2Juice/Test1@main
        with:
          sources: test/test1.txt test/test2.txt
          destination: test/test3.txt

