name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.2

      - name: Write File
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: test-output/out.js
          write-mode: overwrite
          contents: |
            Hello World!
      
      - name: Git Commit Push Action
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          email: ${{ github.actor }}@users.noreply.github.com
          name: ${{ github.actor }}
          commit_message: your_message
          target_branch: main
          #files: file1 file2 directory1 directory2/file3
          remote_repository: https://github.com/Mango2Juice/Test1
          access_token: ${{ github.token }}
          force: true
          empty: true
          tags: true