name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Write File
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: ci/test-output/out.js
          write-mode: append
          contents: |
            Hello World!
      
      - name: Git Commit Push Action
        uses: GuillaumeFalourd/git-commit-push@v1.3